import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, TrendingUp, Lightbulb, FileText, CheckCircle2, ChevronRight, BarChart3, AlertCircle } from 'lucide-react';
import PageTransition from '../components/layout/PageTransition';
import GlassCard from '../components/ui/GlassCard';
import GlowingBadge from '../components/ui/GlowingBadge';
import ShimmerLoader from '../components/ui/ShimmerLoader';
import { getDashboardMetrics } from '../services/api';

const AIInsights = () => {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState(null);

  useEffect(() => {
    const fetchMetrics = async () => {
      try {
        const metrics = await getDashboardMetrics();
        setData(metrics);
      } catch (err) {
        console.error("Failed to load insights:", err);
      } finally {
        setLoading(false);
      }
    };
    fetchMetrics();
  }, []);

  const insightsList = [
    {
      type: "resume",
      title: "Quantify Project Impact",
      desc: "Your projects section has high technical depth, but lacks quantifiable metrics. Bullet points should use the STAR method (e.g. 'Improved efficiency by 15% using Redis caching').",
      impact: "HIGH",
      badgeColor: "orange"
    },
    {
      type: "skills",
      title: "System Design Gap",
      desc: "Based on your target role (SDE-1 at Microsoft), your current profile lists React and Python, but missing basic Low-Level Design (LLD) concepts. Plan to study Design Patterns (Factory, Strategy).",
      impact: "MEDIUM",
      badgeColor: "blue"
    },
    {
      type: "interview",
      title: "Pacing & Code Execution",
      desc: "During mock coding interviews, you explain logic well but write code slowly. Focus on reducing your implementation time. Solve 10 Easy-Medium problems on Leetcode under a strict 20-minute timer.",
      impact: "HIGH",
      badgeColor: "orange"
    },
    {
      type: "companies",
      title: "Google Technical Alignment",
      desc: "Your profile has high alignment with Google's technical hiring bar (90% rating on graphs & trees). We suggest scheduling a mock Google SDE-1 DSA interview now.",
      impact: "LOW",
      badgeColor: "green"
    }
  ];

  return (
    <PageTransition>
      <div className="pt-28 pb-12 px-6 max-w-5xl mx-auto">
        <h1 className="text-3xl font-heading font-bold text-white mb-2">AI Insights & Coaching</h1>
        <p className="text-white/40 mb-8">Personalized coaching suggestions, performance analytics, and actionable focus areas generated by the Placement Agent.</p>

        {loading ? (
          <div className="space-y-4">
            <ShimmerLoader className="h-44 w-full" />
            <ShimmerLoader className="h-60 w-full" />
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Left Column: Index & Statistics summary */}
            <div className="lg:col-span-1 space-y-6">
              <GlassCard hover={false} className="p-6 border-accent-blue/30 glow-blue">
                <h3 className="text-white font-heading font-bold text-sm mb-4 flex items-center gap-2">
                  <BarChart3 className="text-accent-blue" size={16} /> Placement Readiness
                </h3>
                <div className="text-center my-6">
                  <span className="text-5xl font-mono font-bold text-white">{data?.placement_readiness_index || 75.0}%</span>
                  <p className="text-white/40 text-xs mt-2">Overall Score</p>
                </div>
                <div className="space-y-2 border-t border-glass-border pt-4 mt-4 text-xs text-white/60">
                  <div className="flex justify-between">
                    <span>Resume Review Rating</span>
                    <span className="text-white font-mono">{data?.resume_score || 0}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Mock Interview Average</span>
                    <span className="text-white font-mono">{data?.interview_avg_score || 0}%</span>
                  </div>
                  <div className="flex justify-between">
                    <span>Target Companies Prepared</span>
                    <span className="text-white font-mono">{data?.companies_prepared || 0}</span>
                  </div>
                </div>
              </GlassCard>

              <GlassCard hover={false} className="p-6">
                <h3 className="text-white font-heading font-bold text-sm mb-3">Target Profile</h3>
                <p className="text-xs text-white/50 leading-relaxed mb-4">The agent uses this role definition to analyze alignment across DSA, Resume, and System Design rounds.</p>
                <div className="p-4 bg-white/5 border border-glass-border rounded-xl">
                  <span className="text-[10px] text-white/40 font-bold block uppercase">CURRENT GOAL</span>
                  <span className="text-white font-heading font-semibold text-sm mt-1 block">SDE-1 (Microsoft / Google)</span>
                </div>
              </GlassCard>
            </div>

            {/* Right Column: Coaching Insights */}
            <div className="lg:col-span-2 space-y-6">
              <h2 className="text-lg font-heading font-bold text-white mb-2 flex items-center gap-2">
                <Lightbulb className="text-accent-cyan" size={18} /> Actionable Recommendations
              </h2>

              <div className="space-y-4">
                {insightsList.map((ins, i) => (
                  <GlassCard key={i} hover={true} className="p-6">
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex items-center gap-3">
                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${ins.type === 'resume' ? 'bg-accent-blue/10 text-accent-blue' : ins.type === 'skills' ? 'bg-accent-purple/10 text-accent-purple' : 'bg-accent-cyan/10 text-accent-cyan'}`}>
                          {ins.type === 'resume' ? <FileText size={16} /> : ins.type === 'skills' ? <TrendingUp size={16} /> : <Sparkles size={16} />}
                        </div>
                        <h4 className="text-white font-heading font-bold text-sm">{ins.title}</h4>
                      </div>
                      <GlowingBadge text={`${ins.impact} IMPACT`} color={ins.badgeColor} />
                    </div>
                    
                    <p className="text-white/70 text-xs leading-relaxed mb-4">
                      {ins.desc}
                    </p>

                    <div className="flex justify-between items-center text-[10px] text-white/40 border-t border-glass-border/30 pt-3">
                      <span className="flex items-center gap-1"><CheckCircle2 size={12} className="text-accent-green" /> Resolved automatically on re-upload/next mock</span>
                      <button className="text-accent-blue font-semibold hover:underline flex items-center gap-0.5">Focus now <ChevronRight size={10} /></button>
                    </div>
                  </GlassCard>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </PageTransition>
  );
};

export default AIInsights;
